__Finiti gli esercizi, oppure il tempo a disposizione, salvate il notebook usando:__<BR>
```
File --> Save Notebook as
```
__usando il vostro cognome_nome come nome del file. Spedite il notebook, usando il vostro mailer preferito, a maina@to.infn.it, CON IL FILE IN ALLEGATO.__
    
Per determinare la cartella in cui il file viene salvato usate il comando `%pwd` in una cella a parte.

### Esercizio 1
__Scrivete un array `val` di numeri reali compresi fra 20 e 40 ad intervalli di 0.3. 
Costruite una funzione, `pol(x,n2,n1,n0)`, che restituisca l'array dei valori del polinomio
y = n2\*x\*\*2 +n1\*x + n0 in tutti i punti dell'array x. Testate `pol` su un piccolo array per cui siete in grado di calcolare autonomamente il risultato per n2 = n1 = n0 = 1. Usate `pol` per calcolare i valori di 1/2\*x\*\*2 -x + 1 nei punti contenuti in `val`.__   

In [6]:
import numpy as np
import numpy.linalg as LA

val = np.arange(20,41,0.3)

def pol(x,n2,n1,n0):
    y = n2*(x**2) + n1*x + n0
    y1 = (1/2) * (x**2) - x + 1
    return y,y1
pol(val,1/20,0,0) # so che passa per (20,20)

(array([20.    , 20.6045, 21.218 , 21.8405, 22.472 , 23.1125, 23.762 ,
        24.4205, 25.088 , 25.7645, 26.45  , 27.1445, 27.848 , 28.5605,
        29.282 , 30.0125, 30.752 , 31.5005, 32.258 , 33.0245, 33.8   ,
        34.5845, 35.378 , 36.1805, 36.992 , 37.8125, 38.642 , 39.4805,
        40.328 , 41.1845, 42.05  , 42.9245, 43.808 , 44.7005, 45.602 ,
        46.5125, 47.432 , 48.3605, 49.298 , 50.2445, 51.2   , 52.1645,
        53.138 , 54.1205, 55.112 , 56.1125, 57.122 , 58.1405, 59.168 ,
        60.2045, 61.25  , 62.3045, 63.368 , 64.4405, 65.522 , 66.6125,
        67.712 , 68.8205, 69.938 , 71.0645, 72.2   , 73.3445, 74.498 ,
        75.6605, 76.832 , 78.0125, 79.202 , 80.4005, 81.608 , 82.8245]),
 array([181.   , 186.745, 192.58 , 198.505, 204.52 , 210.625, 216.82 ,
        223.105, 229.48 , 235.945, 242.5  , 249.145, 255.88 , 262.705,
        269.62 , 276.625, 283.72 , 290.905, 298.18 , 305.545, 313.   ,
        320.545, 328.18 , 335.905, 343.72 , 351.625, 359.62 , 367.705,
    

### Esercizio 2
__Costruite l'array A di elementi 1/n**2 con n intero compreso fra 1 e 100 compresi. Costruite una funzione a_data(arr) che restituisca il primo e l'ultimo elemento dell'array `arr`. I due valori devono essere divisi per la somma degli elementi di `arr` se il valore assoluto della  differenza fra questa somma e zero è maggiore di `1.e-8`. Testate la funzione con l' array A e con l'array np.array([1,-1]).__

In [16]:
n = np.arange(1,101,1)
A = np.array([1/n**2])

def a_data(arr):   
    if abs(np.sum(arr) - 0) > 1.e-8:
        first = arr[0]/np.sum(arr)
        sec = arr[-1]/np.sum(arr)
    else:
        first = arr[0]
        sec = arr[-1]
    return first,sec

print(a_data(A))
print(a_data(np.array([1,-1])))

(array([6.11626818e-01, 1.52906704e-01, 6.79585353e-02, 3.82266761e-02,
       2.44650727e-02, 1.69896338e-02, 1.24821800e-02, 9.55666903e-03,
       7.55094837e-03, 6.11626818e-03, 5.05476709e-03, 4.24740846e-03,
       3.61909360e-03, 3.12054499e-03, 2.71834141e-03, 2.38916726e-03,
       2.11635577e-03, 1.88773709e-03, 1.69425711e-03, 1.52906704e-03,
       1.38690888e-03, 1.26369177e-03, 1.15619436e-03, 1.06185211e-03,
       9.78602908e-04, 9.04773399e-04, 8.38994263e-04, 7.80136247e-04,
       7.27261377e-04, 6.79585353e-04, 6.36448302e-04, 5.97291814e-04,
       5.61640788e-04, 5.29088943e-04, 4.99287198e-04, 4.71934273e-04,
       4.46769041e-04, 4.23564278e-04, 4.02121511e-04, 3.82266761e-04,
       3.63847006e-04, 3.46727221e-04, 3.30787895e-04, 3.15922943e-04,
       3.02037935e-04, 2.89048591e-04, 2.76879501e-04, 2.65463029e-04,
       2.54738366e-04, 2.44650727e-04, 2.35150641e-04, 2.26193350e-04,
       2.17738276e-04, 2.09748566e-04, 2.02190684e-04, 1.95034062e-04,
     

### Esercizio 3
__Data la matrice:__
$$
R = \left( \begin{matrix}
1 & 3 & 1 & -1 \\
-1 & 2 & 2 & 0\\ 
0 & 2 & -1 & 1\\
-2 & 0 & 1 & -1\\
\end{matrix} \right)
$$

__Verificate che la matrice è invertibile. Sostituite la terza riga della matrice con il doppio della seconda riga.
Verificate se la matrice risultante è invertibile.__

In [21]:
R = np.array([[1,3,1,-1],[-1,2,2,0],[0,2,-1,1],[-2,0,1,-1]])
if LA.det(R) != 0:
    print(R)
    print("R Invertibile!\n")
else:
    print("R Non invertibile \n")
    
R[2] = 2*R[1]
R1 = R

if LA.det(R1) != 0:
    print(R1)
    print("R1 Invertibile!\n")
else:
    print("R1 Non invertibile \n")

[[ 1  3  1 -1]
 [-1  2  2  0]
 [ 0  2 -1  1]
 [-2  0  1 -1]]
R Invertibile!

R1 Non invertibile 



### Esercizio 4
__Scrivete una funzione `mysub(mylist,test=False)` che dato un array `mylist` restituisca la somma S degli elementi di `mylist`. 
Se `test=False` la funzione deve scrivere S nel file `sum.dat`. Se `test=True` la funzione deve stampare S sullo schermo.__<BR>
__Testate `mysub` con l'array `np.array([1,2,3])` sia con `test=False` che con `test=True`.__

In [25]:
def mysub(mylist,test=False):
    S = np.sum(mylist)
    
    if test == False:
        with open("sum.dat","w") as file:
            file.write(str(S))
    else:
        return S

mysub(np.array([1,2,3]))