__Finiti gli esercizi, oppure il tempo a disposizione, salvate il notebook usando:__<BR>
```
File --> Save Notebook as
```
__usando il vostro cognome_nome come nome del file. Spedite il notebook, usando il vostro mailer preferito, a maina@to.infn.it, CON IL FILE IN ALLEGATO.__
    
Per determinare la cartella in cui il file viene salvato usate il comando `%pwd` in una cella a parte.

### Esercizio 1
__Scrivete un array `val` di 101 numeri reali equidistanti fra 20 e 40 inclusi. Costruite una funzione, log_logcube(x), che restituisca il logaritmo e il logaritmo al cubo dei punti in `x`. Testate la funzione su un piccolo array per cui siete in grado di verificare il risultato e poi applicatela su `val`.__   

In [2]:
import numpy as np

#funzione
def log_logcube(x):
    return (np.log(x), np.log(x)**3)

#variabili
val = np.linspace(20,40,101)
test = np.array([np.e, np.e**2, np.e**3])

#chiamo la funzione
print (log_logcube(test), 2*"\n")
print (log_logcube(val))

(array([1., 2., 3.]), array([ 1.,  8., 27.])) 


(array([2.99573227, 3.0056826 , 3.0155349 , 3.02529108, 3.03495299,
       3.04452244, 3.05400118, 3.06339092, 3.07269331, 3.08190997,
       3.09104245, 3.10009229, 3.10906096, 3.11794991, 3.12676054,
       3.13549422, 3.14415228, 3.15273602, 3.16124671, 3.16968558,
       3.17805383, 3.18635263, 3.19458313, 3.20274644, 3.21084365,
       3.21887582, 3.22684399, 3.23474917, 3.24259235, 3.25037449,
       3.25809654, 3.26575941, 3.27336401, 3.28091122, 3.28840189,
       3.29583687, 3.30321697, 3.31054301, 3.31781577, 3.32503602,
       3.33220451, 3.33932198, 3.34638915, 3.35340672, 3.36037539,
       3.36729583, 3.37416871, 3.38099467, 3.38777436, 3.39450839,
       3.40119738, 3.40784192, 3.41444261, 3.42100001, 3.42751469,
       3.4339872 , 3.44041809, 3.44680789, 3.45315712, 3.45946629,
       3.4657359 , 3.47196645, 3.47815842, 3.48431229, 3.49042852,
       3.49650756, 3.50254988, 3.5085559 , 3.51452607, 3.5204608 ,
       3.526

### Esercizio 2
__Scrivete l'array `a1` dei numeri interi fra 100 e 400.  Estraete in un array `b2` gli elementi di `a1` che hanno resto 2 modulo 7. Costruite l'array `b3` degli inversi degli elementi di `b2`.
Costruite l'array `b4` che contiene gli elementi di `b3` in ordine crescente.__

In [49]:
#a1 = array dei numeri interi da 1 a 400
a1 = np.arange(100,401)

#b2 = array dei valori di a1 che, divisi per 7, hanno resto 2
b2 = a1[a1 % 7 == 2]

#b3 = array degli elementi inversi di b2
b3 = 1/b2

#b4 = array degli elementi di b3 sistemati in ordine crescente
b4 = np.sort(b3)

array([0.00253807, 0.00258398, 0.00263158, 0.00268097, 0.00273224,
       0.00278552, 0.00284091, 0.00289855, 0.00295858, 0.00302115,
       0.00308642, 0.00315457, 0.00322581, 0.00330033, 0.00337838,
       0.00346021, 0.0035461 , 0.00363636, 0.00373134, 0.00383142,
       0.00393701, 0.00404858, 0.00416667, 0.00429185, 0.00442478,
       0.00456621, 0.00471698, 0.00487805, 0.00505051, 0.0052356 ,
       0.00543478, 0.00564972, 0.00588235, 0.00613497, 0.00641026,
       0.00671141, 0.00704225, 0.00740741, 0.0078125 , 0.00826446,
       0.00877193, 0.00934579, 0.01      ])

### Esercizio 3
__Risolvere il sistema di equazioni:__
$$x+2y +3z=2$$ 
$$-x+y-2z+5t=0$$
$$x+ y-z +t=-4$$
$$2y-3z-t=-1$$
__Verificare che la soluzione trovata soddisfa le equazioni di partenza.__

In [4]:
A = np.array([[1,2,3,0],[-1,1,-2,5],[1,1,-1,1],[0,2,-3,-1]]) #matrice dei coefficienti
b = np.array([2.,0.,-4.,-1.]) #vettore dei termini noti

inc = LA.solve(A,b) #vettore delle incognite

print(f"{np.dot(A,inc)} = {b}") #verifica visiva

[ 2.0000000e+00 -4.4408921e-16 -4.0000000e+00 -1.0000000e+00] = [ 2.  0. -4. -1.]


### Esercizio 4
__Scrivete una funzione `func(x,shift=False)` che dato un array `x` restituica l'array `x2` dei quadrati dei valori in `x`. Se e solo se `shift=True` func deve sottrarre 5 a tutti gli elementi di `x2`.__<BR>
__Testate `func` su `numpy.arange(1,10,0.3)`.__

In [50]:
#definire la funzione
def func(x,shift=False):
    x2 = x**2
    if shift == True:
        x2 -= 5
    return x2

#testare la funzione
x = np.arange(1,10,0.3)
list(zip(func(x),func(x, shift = True))) #in questo caso si legge meglio se non si usa la funzione print()

[(1.0, -4.0),
 (1.6900000000000002, -3.3099999999999996),
 (2.5600000000000005, -2.4399999999999995),
 (3.6100000000000003, -1.3899999999999997),
 (4.840000000000001, -0.15999999999999925),
 (6.25, 1.25),
 (7.840000000000002, 2.8400000000000016),
 (9.610000000000003, 4.610000000000003),
 (11.560000000000002, 6.560000000000002),
 (13.690000000000001, 8.690000000000001),
 (16.0, 11.0),
 (18.490000000000006, 13.490000000000006),
 (21.160000000000004, 16.160000000000004),
 (24.010000000000005, 19.010000000000005),
 (27.04000000000001, 22.04000000000001),
 (30.25000000000001, 25.25000000000001),
 (33.64000000000001, 28.640000000000008),
 (37.21000000000001, 32.21000000000001),
 (40.96000000000001, 35.96000000000001),
 (44.890000000000015, 39.890000000000015),
 (49.000000000000014, 44.000000000000014),
 (53.29000000000001, 48.29000000000001),
 (57.76000000000002, 52.76000000000002),
 (62.41000000000002, 57.41000000000002),
 (67.24000000000002, 62.24000000000002),
 (72.25, 67.25),
 (77.440000