__Finiti gli esercizi, oppure il tempo a disposizione, salvate il notebook usando:__<BR>
```
File --> Save Notebook as
```
__usando il vostro cognome_nome come nome del file. Spedite il notebook, usando il vostro mailer preferito, a maina@to.infn.it, CON IL FILE IN ALLEGATO.__
    
Per determinare la cartella in cui il file viene salvato usate il comando `%pwd` in una cella a parte.

### Esercizio 1
__Costruite un array `myval` di 101 valori equidistanti fra $-\pi$ e $\pi$.
Costruite una funzione, `sin_sinsq(x)`, che restituisca l'array `s1` dei seni degli elementi di x e l'array `s2` dei seni al quadrato degli elementi di x. Testate la funzione con un piccolo array per cui potete verificare il risultato e poi su `myval`.__   

In [1]:
import numpy as np
import numpy.linalg as LA

myval = np.linspace(-np.pi,np.pi,101)
x = np.array([np.pi/4,np.pi/2,np.pi])
def sin_sinsq(x):
    s1 = np.sin(x)
    s2 = np.sin(x)**2
    return s1,s2
sin_sinsq(x)

(array([7.07106781e-01, 1.00000000e+00, 1.22464680e-16]),
 array([5.00000000e-01, 1.00000000e+00, 1.49975978e-32]))

### Esercizio 2
__Scrivete l'array `a1` dei numeri interi fra 10 e 270 incluso.  Estraete in un array `b2` gli elementi di `a1` che sono divisibili per 15. Costruite l'array `b3` invertendo l'ordine degli elementi di `b2`.
Costruite l'array `b4` dividendo l'array `b3` per l'array dei quadrati degli elementi di `b2`.__

In [9]:
a1 = np.arange(10,271,1)
b2 = a1[a1%15 == 0]
b3 = b2[::-1]
b4 = b3 / (b2**2)
print("Divisibili per 15",b2)
print("b2 in ordine inverso")
print(b4)

[ 15  30  45  60  75  90 105 120 135 150 165 180 195 210 225 240 255 270]
[270 255 240 225 210 195 180 165 150 135 120 105  90  75  60  45  30  15]
[1.20000000e+00 2.83333333e-01 1.18518519e-01 6.25000000e-02
 3.73333333e-02 2.40740741e-02 1.63265306e-02 1.14583333e-02
 8.23045267e-03 6.00000000e-03 4.40771350e-03 3.24074074e-03
 2.36686391e-03 1.70068027e-03 1.18518519e-03 7.81250000e-04
 4.61361015e-04 2.05761317e-04]


### Esercizio 2
__Data la matrice:__
$$
R = \left( \begin{matrix}
1 & 3 & 1 & -1 \\
-1 & 2 & 2 & 0\\ 
0 & 2 & -1 & 1\\
-2 & 0 & 1 & -1\\
\end{matrix} \right)
$$

__Verificate che la matrice è invertibile. Calcolate la matrice inversa `Rinv` e usate `Rinv` per risolvere
i sistemi di equazioni lineari R\*X=B1 e R\*X=B2 con B1 = [3,1.5,2,-1.2] e B2 = [10,0.1,-2,1]. X è il vettore delle incognite.
Verificate che i risultati S1 e S2 soddisfano le equazioni R\*S1=B1 e R\*S2=B2__

In [49]:
R = np.array([[1,3,1,-1],[-1,2,2,0],[0,2,-1,1],[-2,0,1,-1]])
LA.det(R) # det non 0 quindi invertibile
R = LA.inv(R)

B1 = [3,1.5,2,-1.2]
B2 = [10,0.1,-2,1]

# RX = B1
S1 = LA.solve(R,B1)

# RX = B2
S2 = LA.solve(R,B2)

print("Le soluzioni S1 e S2 sono: ",S1,S2)
print("B1 = ",B1)
print("R*S1 = ",np.dot(R,S1))
print("B2 = ",B2)
print("R*S2 = ",np.dot(R,S2))

Le soluzioni S1 e S2 sono:  [10.7  4.  -0.2 -2.8] [  7.3 -13.8   3.2 -23. ]
B1 =  [3, 1.5, 2, -1.2]
R*S1 =  [ 3.   1.5  2.  -1.2]
B2 =  [10, 0.1, -2, 1]
R*S2 =  [10.   0.1 -2.   1. ]


### Esercizio 4
__Scrivete una funzione `ff(x,normalize=True)` che dato un array `x` restituisca l'array `x4` delle quarte potenze dei valori in `x`.  Se `normalize=True` `ff` Il vettore `x4` deve essere diviso per la somma dei suoi elementi__<BR>
__Testate `ff` su `np.array([-2,1,-0.1,4.2,0,1.2,-0.5,0.4,-1.3])` sia nel caso `normalize=True` che nel caso `normalize=False`.__

In [56]:
def ff(x,normalize=True):
    x4 = x**4
    if normalize == True:
        x4 = x4/np.sum(x4)
    else:
        x4 = x4
    return x4
ff(np.array([-2,1,-0.1,4.2,0,1.2,-0.5,0.4,-1.3]),normalize=True)



array([4.80210092e-02, 3.00131307e-03, 3.00131307e-07, 9.33917389e-01,
       0.00000000e+00, 6.22352279e-03, 1.87582067e-04, 7.68336147e-05,
       8.57205027e-03])